set_property PACKAGE_PIN R2 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]

set_property PACKAGE_PIN C8 [get_ports led_1]
set_property IOSTANDARD LVCMOS33 [get_ports led_1]
set_property PACKAGE_PIN D8 [get_ports led_2]
set_property IOSTANDARD LVCMOS33 [get_ports led_2]

set_property PACKAGE_PIN H18 [get_ports reset_n]
set_property IOSTANDARD LVCMOS33 [get_ports reset_n]

set_property PACKAGE_PIN B14 [get_ports LCD_RS]
set_property IOSTANDARD LVCMOS33 [get_ports LCD_RS]

set_property PACKAGE_PIN A13 [get_ports LCD_CS]
set_property IOSTANDARD LVCMOS33 [get_ports LCD_CS]

set_property PACKAGE_PIN C13 [get_ports LCD_WR]
set_property IOSTANDARD LVCMOS33 [get_ports LCD_WR]

set_property PACKAGE_PIN C14 [get_ports LCD_RESET]
set_property IOSTANDARD LVCMOS33 [get_ports LCD_RESET]

set_property PACKAGE_PIN G15 [get_ports LCD_BL]
set_property IOSTANDARD LVCMOS33 [get_ports LCD_BL]

set_property PACKAGE_PIN B15 [get_ports LCD_RDX]
set_property IOSTANDARD LVCMOS33 [get_ports LCD_RDX]

set_property PACKAGE_PIN B16 [get_ports {LCD_DATA[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_DATA[0]}]
set_property PACKAGE_PIN A14 [get_ports {LCD_DATA[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_DATA[1]}]
set_property PACKAGE_PIN B17 [get_ports {LCD_DATA[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_DATA[2]}]
set_property PACKAGE_PIN A15 [get_ports {LCD_DATA[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_DATA[3]}]
set_property PACKAGE_PIN D15 [get_ports {LCD_DATA[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_DATA[4]}]
set_property PACKAGE_PIN C16 [get_ports {LCD_DATA[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_DATA[5]}]
set_property PACKAGE_PIN E15 [get_ports {LCD_DATA[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_DATA[6]}]
set_property PACKAGE_PIN A17 [get_ports {LCD_DATA[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_DATA[7]}]
set_property PACKAGE_PIN G16 [get_ports {LCD_DATA[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_DATA[8]}]
set_property PACKAGE_PIN D16 [get_ports {LCD_DATA[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_DATA[9]}]
set_property PACKAGE_PIN H16 [get_ports {LCD_DATA[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_DATA[10]}]
set_property PACKAGE_PIN E16 [get_ports {LCD_DATA[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_DATA[11]}]
set_property PACKAGE_PIN C18 [get_ports {LCD_DATA[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_DATA[12]}]
set_property PACKAGE_PIN F15 [get_ports {LCD_DATA[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_DATA[13]}]
set_property PACKAGE_PIN E17 [get_ports {LCD_DATA[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_DATA[14]}]
set_property PACKAGE_PIN C17 [get_ports {LCD_DATA[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LCD_DATA[15]}]

set_property PACKAGE_PIN D14 [get_ports lcd_clk]
set_property IOSTANDARD LVCMOS33 [get_ports lcd_clk]
